site:
  title: KEVIN TRUONG BLOGS
  url: https://ravstudio.me
  start_page: home::index.adoc
content:
  branches: release/*
  sources:
  - url: .
    branches: HEAD
    start_path: home
  - url: ./eframework
#    branches: master
    start_path: docs
asciidoc:
  attributes:
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    tabs: tabs
    toc: ~
    xrefstyle: short
    plantuml-server-url: 'http://www.plantuml.com/plantuml'
    plantuml-fetch-diagram: true
  extensions:
  - ./lib/json-config-ui-block-macro.js
  - ./lib/inline-man-macro.js
  - ./lib/multirow-table-head-tree-processor.js
  - ./lib/swagger-ui-block-macro.js
  - ./lib/tabs-block.js
  - asciidoctor-plantuml
ui:
  bundle:
    url: ./ui-bundle.zip
  output_dir: _/ui
  supplemental_files:
  - path: robots.txt
    contents: |
      User-agent: *
      Disallow: /
  - path: ui.yml
    contents: |
      static_files: [robots.txt]
output:
  dir: ./public
