= Welcome to Kevin Truong Blogs!
:page-layout: home
:!sectids:

I do love writing recently,
My wife is designer, she also love to have
personal website to present many project she already done. But there have problems
that is she is using Wordpress to make her website. And I have trouble with it.
feel complicated to configure, backup to bringe up a website. And then , when
everything done, need to move the current webstite from the host to another it realy annoying me.
Luckily that I found a really great platform for documentation, call antora,
basically, it based on asciidoc and a lot of work to make a documentation platform to be exist.
I was looking around github and another resources to see what `antora` can be done. and be excited about
what it can do.
Form there, I also have an ideal about simple blog platfom using antora to solve my
wife (also myself) problems is create a simple blog platform hosting in
S3 (static web), using git as CRM module, Using asciidoc for formating.
I also found out that the ideal already work by `COUCHBASE` , they already done with
their docs website. and It means I will save lot of works by re-use they work
basically, just edit the `ui-bundle` and add some python/shell script for auto deploy
the work to S3, maybe something like DEVOPS for auto update the new/modify blog whenever
I make a change in my github CRM

[.cards.cards-2.personas.conceal-title]
== {empty}

[.card]
=== Knowledge Base

My write for engineer life

* xref:knowledge-base:eFramework-my-embedded-framework.adoc[eFramework - A tiny embedded framework]
* xref:knowledge-base:embedded-c-object-oriented-programming.adoc[Embedded C,Object oriented programming - HOW TO]
* xref:knowledge-base:design-of-everything.adoc[Design of Everything]

[.card]
=== Contribute

If you are interesting with my work please following the guideline bellow for contributing

* xref:contribute:add-pages.adoc[Add Pages]
* xref:contribute:asciidoc-overview.adoc[AsciiDoc Overview]
* xref:contribute:attributes-and-roles.adoc[Attributes and Roles]
* xref:contribute:basics.adoc[Basics]

<<<

== My Open Source Project

[.card-lifestyle]
=== eFramework

All write related to my working on eFramework

* xref:e-framework::index.adoc[eFramework Home]
* xref:e-framework::eframework-my-embedded-framework.adoc[eFramework architecture]


== Welcome to my Blogs

[.card-travel]
=== My Life Style

Love travel a lot

* xref:travel:index.adoc[Ta Nang Phan Dung Trekking]

[.tiles.browse]
== My Work

[.tile]
.STYL
* xref:my-work:STYL.adoc[My Work At STYL]

[.tile]
.ELinkGate
* xref:my-work:ELINKGATE.adoc[My Work At ELINKGATE]

[.tile]
.Raven
* xref:my-work:RAVEN.adoc[My Work At Raven]

[.tile]
.VEriK Systems
* xref:my-work:VEriKSystems.adoc[My Work At VRIKSystems]
